name: ArmorStandEditor
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
version: 1.18.2-34
api-version: "1.13"
website: https://www.spigotmc.org/resources/94503/
author: Wolfstorm
authors: [Wolfstorm, Marfjeh, miknes123, rypofalem, sekwah41, Sikatsu1997, Cool_boy, sumdream, Amaury Carrade, nicuch, kotarobo, prettydude, Jumpy91, Niasio, Patbox, Puremin0rez, Prof-Bloodstone]
description: Allows players to edit data of armorstands without any commands.
softdepend: [Towny]
commands:
  ase:
    description: Changes the function of the armorstand edit tool.
    usage: /<command> ? - list subcommands
    aliases: [ase, asedit, armorstandeditor]
    permission: asedit.basic
    permission-message: "You are lacking the permission node 'asedit.basic'"
permissions:
    asedit.basic:
      description: Allow use armorstand edit functions. If set to false it will override all other functions.
      default: true
    asedit.armorstand.invisible:
      description: Toggles ArmorStand visibility.
      default: true
    asedit.itemframe.invisible:
      description: Allows setting of ItemFrame Visibility
      default: true
    asedit.rename:
      description: Rename armorstands - Now Supports Color
      default: true
    asedit.equipment:
      description: Access armorstand equipment GUI
      default: true
    asedit.disableslots:
      description: Allows locking and unlocking the contents of an ArmorStand. When locked, armor and equipement can not be added or removed without unlocking it first.
      default: true
    asedit.update:
      description: Allows the checking for updates.
      default: false