name: ArmorStandEditor
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
version: 1.16-24
api-version: "1.13"
website: rypofalem.github.io
author: RypoFalem
description: Allows players to edit data of armorstands without any commands.
commands:
  ase:
    description: Changes the function of the armorstand edit tool.
    usage: /<command> ? - list subcommands
    permission: asedit.basic
permissions:
    asedit.basic:
      desciption: Allow use armorstand edit functions. If set to false it will override all other functions.
      default: true
    asedit.invisible:
      description: Toggle armorstand visible/invisible.
      default: true
    asedit.rename:
      description: Rename armorstands
      default: true
