name: ArmorStandEditor
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
version: 1.17-29
api-version: "1.13"
website: rypofalem.github.io
authors:
  - Rypofalem
  - Wolfstorm
  - Marfjeh
description: Allows players to edit data of armorstands without any commands.
commands:
  ase:
    description: Changes the function of the armorstand edit tool.
    usage: /<command> ? - list subcommands
    permission: asedit.basic
permissions:
    asedit.basic:
      description: Allow use armorstand edit functions. If set to false it will override all other functions.
      default: true
    asedit.invisible:
      description: Toggle armorstand visible/invisible.
      default: true
    asedit.rename:
      description: Rename armorstands
      default: true
    asedit.equipment:
      description: Access armorstand equipment GUI
      default: true
    asedit.reload:
      description: Reload Configs for ArmorStandEditor
      default: false