name: ArmorStandEditor
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
version: 1.8-0.1.6BETA
website: rypofalem.github.io
author: RypoFalem
description: Allows players to edit certain NBT tags of armorstands without any commands.
softdepend: [WorldGuard,PlotSquared,GriefPrevention]
commands:
  ase:
    description: Changes the function of the armorstand edit tool.
    usage: /<command> ? - list subcommands
    permissions: asedit.basic
permissions:
    asedit.all:
      description: Permit ALL the things!
      default: op
      children:
        asedit.basic: true
        asedit.copy: true
        asedit.showarms: true
        asedit.invisible: true
        asedit.size: true
        asedit.baseplate: true
        asedit.gravity: true
        asedit.head: true
        asedit.body: true
        asedit.rightarm: true
        asedit.leftarm: true
        asedit.rightleg: true
        asedit.leftleg: true
        asedit.placement: true
    asedit.basic:
      desciption: Allow use armorstand edit functions. If set to false it will override all other functions.
      default: op
    asedit.copy:
      description: Allows use of the copy/paste settings fuction.
      default: op
    asedit.showarms:
      description: Toggle arms on/off.
      default: op
    asedit.invisible:
      description: Toggle armorstand visible/invisible.
      default: op
    asedit.size:
      description: Toggle armorstand size normal/small.
      default: op
    asedit.baseplate:
      description: Toggle baseplate visible/invisible.
      default: op
    asedit.gravity: 
      description: Toggle falling/floating armorstand.
      default: op
    asedit.placement:
      description: Adjust armorstand's location.
      default: op
    asedit.head:
      description: Adjust head position.
      default: op
    asedit.body:
      description: Adjust body position.
      default: op
    asedit.positionarms:
      description: Adjust arm position.
      default: op
      children:
      asedit.leftarm: true
      asedit.rightarm: true
    asedit.positionlegs:
      description: Adjust leg position.
      default: op
      children:
      asedit.leftleg: true
      asedit.rightleg: true
    asedit.leftarm:
      description: Adjust left arm position
      default: op
    asedit.rightarm:
      description: Adjust right arm position
      default: op
    asedit.leftleg: 
      description: Adjust left leg position
      default: op
    asedit.rightleg:
      description: Adjust right leg position
      default: op
