name: Behavior Bug or other issue
description: Report issues with the plugin or other behavior related issues.
labels: ["bug", "BUG-0: Pending Investigation"]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a crash here, please make sure you are on the latest version of the Plugin.
        Forks of the plugin receive no support here. If you are using a fork, please make sure that this issue also happens when using the latest release.

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin Version
      description: What version of the Plugin are you using for this? As of 1.18, you can get this via /ase version.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Server Version
      description: What Server Backend are you using? Put your output of /version ingame here
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false